### ISSUE TITLE
Python AppImage on Travis CI

### ISSUE THREAD

**Issue by ghost** [probonopd/font-leutkirch#14]
From [`.travis.yml`](https://github.com/probonopd/font-leutkirch/blob/master/.travis.yml):

```YAML
language: minimal
dist: bionic

script:
  - sudo apt-get -y install python3-pip python3-setuptools python3-wheel # fontforge
  - sudo pip3 install afdko
```

Why not use `python3.*.AppImage`?

- https://twitter.com/probonopd/status/1248501732843220993
- https://github.com/niess/python-appimage/releases
